CREATE TABLE public.endereco (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cidade varchar(50) NOT NULL,
    uf varchar(2) NOT NULL,
    logradouro varchar(200),

    CONSTRAINT pk_endereco_id PRIMARY KEY (id)
);