CREATE TABLE public.fazenda (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome varchar(200),
    cnpj varchar(18),
    endereco_id bigint NOT NULL,

    CONSTRAINT pk_fazenda_id PRIMARY KEY (id),
    FOREIGN KEY (ENDERECO_ID) REFERENCES endereco (ID)
);